image_vote:
  repository: dockersamples/examplevotingapp_vote
  pullPolicy: "IfNotPresent"
  port: 5000
  targetPort: 80
  nodePort: 31000
  replicas: 1
  tag: "before"

image_result:
  repository: dockersamples/examplevotingapp_result
  pullPolicy: "IfNotPresent"
  port: 5001
  targetPort: 80
  nodePort: 31001
  replicas: 1
  tag: "before"

image_worker:
  repository: dockersamples/examplevotingapp_worker
  pullPolicy: "IfNotPresent"
  replicas: 1

image_redis:
  repository: redis:alpine
  pullPolicy: "IfNotPresent"

image_db:
  repository: postgres
  pullPolicy: "IfNotPresent"
  tag: "9.4"

appVersion:
  tag: "1.16.0"