image_db:
  pullPolicy: IfNotPresent
  repository: postgres
  tag: '9.4'
image_redis:
  pullPolicy: IfNotPresent
  repository: redis:alpine
image_result:
  nodePort: 31001
  port: 5001
  pullPolicy: IfNotPresent
  replicas: 1
  repository: liorbenami/result
  tag: '0.5'
  targetPort: 80
image_vote:
  nodePort: 31000
  port: 5000
  pullPolicy: IfNotPresent
  replicas: 1
  repository: liorbenami/vote
  tag: '1.10'
  targetPort: 80
image_worker:
  pullPolicy: IfNotPresent
  replicas: 1
  repository: liorbenami/worker
  tag: '0.2'
appVersion:
  tag: "1.16.0"
