apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: "{{ .Values.image_result.port}}"
    targetPort: "{{ .Values.image_result.targetPort}}"
    nodePort: "{{ .Values.image_result.nodePort}}"
  selector:
    app: result
