apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  replicas: {{ .Values.image_result.replicas}}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: "{{ .Values.image_result.repository}}:{{ .Values.image_result.tag}}"
        imagePullPolicy: {{ .Values.image_result.pullPolicy }}
        name: result
        ports:
        - containerPort: 80
          name: result
